name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file SistemProg2021YazWeb/Dockerfile --tag barankaynak/sistemweb2021yaz:latest
    - name: Dockerhub Login
      env:
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      run: docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
    - name: Publish
      run: docker push barankaynak/sistemweb2021yaz:latest
